<!DOCTYPE html>
<html>
<head>
    <title>Batches Export</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h2 { margin: 0; color: #1e293b; }
        .header p { margin: 5px 0; color: #64748b; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
        th { bg-color: #f8fafc; font-weight: bold; color: #475569; }
        .footer { margin-top: 30px; text-align: right; font-size: 10px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Batch Management Report</h2>
        <p>Exported on: {{ date('d M, Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Batch Name</th>
                <th>Subject</th>
                <th>Fees</th>
                <th>Students</th>
                <th>Capacity</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
            @foreach($batches as $batch)
            <tr>
                <td>{{ $batch->id }}</td>
                <td>{{ $batch->name }}</td>
                <td>{{ $batch->subject }}</td>
                <td>Rs. {{ number_format($batch->fees, 2) }}</td>
                <td>{{ $batch->students_count }}</td>
                <td>{{ $batch->max_capacity }}</td>
                <td>{{ $batch->start_time }} - {{ $batch->end_time }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Fee Easy SaaS
    </div>
</body>
</html>
