<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\ExpenseCategory;
use App\Models\Expense;
use Illuminate\Support\Carbon;

class InstituteExpenseController extends Controller
{
    /**
     * Get all expense categories.
     */
    public function getCategories(Request $request)
    {
        $institute = $request->user();
        $categories = $institute->expenseCategories()->orderBy('name', 'asc')->get();

        return response()->json([
            'status' => 'success',
            'data' => $categories
        ]);
    }

    /**
     * Add a built-in category.
     */
    public function storeCategory(Request $request)
    {
        $institute = $request->user();

        $request->validate([
            'name' => 'required|string|max:255'
        ]);

        $category = $institute->expenseCategories()->create([
            'name' => $request->name
        ]);

        return response()->json([
            'status' => 'success',
            'message' => 'Category created successfully.',
            'data' => $category
        ], 201);
    }

    /**
     * Get all expenses (with optional date filtering).
     */
    public function index(Request $request)
    {
        $institute = $request->user();
        
        $query = $institute->expenses()->with('category');

        if ($request->has('start_date') && $request->has('end_date')) {
            $query->whereBetween('date', [$request->start_date, $request->end_date]);
        }

        if ($request->has('category_id')) {
            $query->where('expense_category_id', $request->category_id);
        }

        $paginator = $query->orderBy('date', 'desc')->paginate(15);

        return response()->json([
            'status' => 'success',
            'data' => [
                'items' => $paginator->items(),
                'total' => $paginator->total(),
                'current_page' => $paginator->currentPage(),
                'last_page' => $paginator->lastPage(),
                'per_page' => $paginator->perPage(),
            ]
        ]);
    }

    /**
     * Store a new expense.
     * Note: File upload for receipt_image can be added here if needed using Storage::put()
     */
    public function store(Request $request)
    {
        $institute = $request->user();

        $request->validate([
            'expense_category_id' => 'required|exists:expense_categories,id,institute_id,' . $institute->id,
            'amount' => 'required|numeric|min:0',
            'date' => 'required|date',
            'description' => 'nullable|string',
            'receipt_image' => 'nullable|string' // Wait for direct S3 or Storage disk setup in future
        ]);

        $expense = $institute->expenses()->create([
            'expense_category_id' => $request->expense_category_id,
            'amount' => $request->amount,
            'date' => $request->date,
            'description' => $request->description,
            'receipt_image' => $request->receipt_image,
        ]);

        $expense->load('category');

        return response()->json([
            'status' => 'success',
            'message' => 'Expense added successfully.',
            'data' => $expense
        ], 201);
    }

    /**
     * Update an expense.
     */
    public function update(Request $request, $id)
    {
        $institute = $request->user();

        $expense = $institute->expenses()->findOrFail($id);

        $request->validate([
            'expense_category_id' => 'sometimes|required|exists:expense_categories,id,institute_id,' . $institute->id,
            'amount' => 'sometimes|required|numeric|min:0',
            'date' => 'sometimes|required|date',
            'description' => 'nullable|string',
            'receipt_image' => 'nullable|string'
        ]);

        $expense->update($request->all());

        $expense->load('category');

        return response()->json([
            'status' => 'success',
            'message' => 'Expense updated successfully.',
            'data' => $expense
        ]);
    }

    /**
     * Delete an expense.
     */
    public function destroy(Request $request, $id)
    {
        $institute = $request->user();

        $expense = $institute->expenses()->findOrFail($id);
        $expense->delete();

        return response()->json([
            'status' => 'success',
            'message' => 'Expense deleted successfully.'
        ]);
    }

    /**
     * Expense Report generated by category.
     */
    public function report(Request $request)
    {
        $institute = $request->user();

        $request->validate([
            'start_date' => 'required|date',
            'end_date' => 'required|date'
        ]);

        $expenses = $institute->expenses()
            ->with('category')
            ->whereBetween('date', [$request->start_date, $request->end_date])
            ->get();

        $groupedByCategory = $expenses->groupBy('expense_category_id');

        $report = [];
        $totalOverall = 0;

        foreach ($groupedByCategory as $categoryId => $categoryExpenses) {
            $categoryTotal = $categoryExpenses->sum('amount');
            $totalOverall += $categoryTotal;

            $report[] = [
                'category_id' => $categoryId,
                'category_name' => $categoryExpenses->first()->category->name ?? 'Unknown',
                'total_amount' => $categoryTotal,
                'expense_count' => $categoryExpenses->count()
            ];
        }

        return response()->json([
            'status' => 'success',
            'report_period' => [
                'start_date' => $request->start_date,
                'end_date' => $request->end_date
            ],
            'total_expense' => $totalOverall,
            'breakdown' => $report
        ]);
    }
}
