<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Expense Report - {{ $institute->name }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #1e293b; line-height: 1.5; margin: 0; padding: 0; }
        .container { padding: 40px; }
        .header { border-bottom: 2px solid #A8440B; padding-bottom: 20px; margin-bottom: 30px; }
        .header-title { font-size: 24px; font-weight: bold; color: #A8440B; margin: 0; }
        .header-subtitle { font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 1px; margin-top: 5px; }
        
        .info-grid { width: 100%; margin-bottom: 30px; }
        .info-label { font-size: 10px; font-weight: bold; color: #94a3b8; text-transform: uppercase; margin-bottom: 5px; }
        .info-value { font-size: 14px; font-weight: bold; color: #1e293b; }
        
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th { background-color: #f8fafc; color: #64748b; font-size: 10px; font-weight: bold; text-transform: uppercase; text-align: left; padding: 12px; border-bottom: 1px solid #e2e8f0; }
        td { padding: 12px; font-size: 12px; border-bottom: 1px solid #f1f5f9; color: #334155; }
        .amount { text-align: right; font-weight: bold; }
        .total-row { background-color: #fffaf5; font-weight: bold; }
        .total-label { text-align: right; color: #A8440B; }
        .total-amount { text-align: right; color: #A8440B; font-size: 16px; }
        
        .footer { position: fixed; bottom: 30px; width: 100%; text-align: center; font-size: 10px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1 class="header-title">{{ $institute->name }}</h1>
            <p class="header-subtitle">Expense Report - {{ $period }}</p>
        </div>

        <table class="info-grid">
            <tr>
                <td style="border:0; padding:0; width: 33%;">
                    <div class="info-label">Report Date</div>
                    <div class="info-value">{{ date('d M, Y') }}</div>
                </td>
                <td style="border:0; padding:0; width: 33%;">
                    <div class="info-label">Institute ID</div>
                    <div class="info-value">#{{ $institute->id }}</div>
                </td>
                <td style="border:0; padding:0; text-align: right;">
                    <div class="info-label">Total Categories</div>
                    <div class="info-value">{{ count($breakdown) }}</div>
                </td>
            </tr>
        </table>

        <h3>Summary by Category</h3>
        <table>
            <thead>
                <tr>
                    <th>Category Name</th>
                    <th style="text-align: center;">Transaction Count</th>
                    <th class="amount">Total Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($breakdown as $item)
                <tr>
                    <td>{{ $item['category_name'] }}</td>
                    <td style="text-align: center;">{{ $item['expense_count'] }}</td>
                    <td class="amount">₹{{ number_format($item['total_amount'], 2) }}</td>
                </tr>
                @endforeach
                <tr class="total-row">
                    <td colspan="2" class="total-label">Overall Total Spending</td>
                    <td class="total-amount">₹{{ number_format($total_expense, 2) }}</td>
                </tr>
            </tbody>
        </table>

        @if(isset($expenses) && count($expenses) > 0)
        <h3 style="margin-top: 40px;">Detailed Transactions</h3>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Category</th>
                    <th>Description</th>
                    <th>Method</th>
                    <th class="amount">Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($expenses as $expense)
                <tr>
                    <td>{{ date('d-m-Y', strtotime($expense->date)) }}</td>
                    <td>{{ $expense->category->name ?? 'Uncategorized' }}</td>
                    <td>{{ $expense->description }}</td>
                    <td>{{ $expense->payment_method }}</td>
                    <td class="amount">₹{{ number_format($expense->amount, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
        @endif
    </div>

    <div class="footer">
        Generated by Tuoora ERP • {{ date('Y') }}
    </div>
</body>
</html>
