@extends('layouts.email')

@section('content')
<table role="presentation" class="em-wrap" width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center">
  <table role="presentation" class="em-card" width="600" cellpadding="0" cellspacing="0">
    <!-- INSTITUTE HEADER -->
    <tr><td class="em-header-inst">
      @if(!empty($instituteLogoUrl))
        <img class="em-inst-logo" src="{{ $instituteLogoUrl }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @else
        <div class="em-inst-logo-fallback">{{ strtoupper(substr($instituteName, 0, 1)) }}</div>
      @endif
      <p class="em-inst-name">{{ $instituteName }}</p>
      <p class="em-inst-sub">Fee Invoice</p>
    </td></tr>
    <tr><td class="em-banner"></td></tr>
    
    <!-- BODY -->
    <tr><td class="em-body">
      <div class="em-icon" style="background:#eef2fb;color:#3b5bdb;">&#129534;</div>
      <h1 class="em-title">Fee Invoice</h1>
      <p class="em-sub">A new invoice has been generated by {{ $instituteName }}.</p>
      <p>Hi <strong>{{ $studentName }}</strong>,</p>
      
      <table class="em-meta" role="presentation">
        <tr>
          <td>Invoice No: <strong>{{ $invoiceNo }}</strong></td>
          <td class="r">Date: {{ $invoiceDate }}</td>
        </tr>
        <tr>
          <td>Due Date: <strong>{{ $dueDate }}</strong></td>
          <td class="r">Status: 
            @if($status == 'Paid')
              <span style="color:#1f9d55;font-weight:600;">{{ $status }}</span>
            @elseif($status == 'Partial')
              <span style="color:#f5a623;font-weight:600;">{{ $status }}</span>
            @else
              <span style="color:#d9534f;font-weight:600;">{{ $status }}</span>
            @endif
          </td>
        </tr>
      </table>
      
      <table class="em-inv" role="presentation">
        <tr>
          <th>Description</th>
          <th style="text-align:right;">Amount</th>
        </tr>
        <tr>
          <td>{{ $feeItem1 }}</td>
          <td style="text-align:right;">₹{{ number_format($amount1, 2) }}</td>
        </tr>
        @if($amount2 > 0)
        <tr>
          <td>{{ $feeItem2 }}</td>
          <td style="text-align:right;">₹{{ number_format($amount2, 2) }}</td>
        </tr>
        @endif
        <tr>
          <td>Tax / GST</td>
          <td style="text-align:right;">₹{{ number_format($tax, 2) }}</td>
        </tr>
        <tr class="total">
          <td>Total Due</td>
          <td style="text-align:right;">₹{{ number_format($total, 2) }}</td>
        </tr>
      </table>
      
      @if($status != 'Paid')
        <div class="em-center"><a href="{{ $paymentUrl }}" class="em-btn">Pay Now</a></div>
        <div class="em-note">Please complete the payment before the due date to avoid late charges. For any queries regarding this invoice, contact your institute.</div>
      @else
        <div class="em-center"><a href="{{ $paymentUrl }}" class="em-btn">View Receipt</a></div>
        <div class="em-note">Thank you! This invoice has been fully paid. No further action is required.</div>
      @endif
    </td></tr>
    
    <!-- FOOTER -->
    <tr><td class="em-footer-min">
      <p class="gen">Generated by <strong>Tuoora</strong></p>
    </td></tr>
  </table>
</td></tr>
</table>
@endsection
