@extends('layouts.email')

@section('content')
<table role="presentation" class="em-wrap" width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center">
  <table role="presentation" class="em-card" width="600" cellpadding="0" cellspacing="0">
    <!-- INSTITUTE HEADER -->
    <tr><td class="em-header-inst">
      @if(!empty($instituteLogoPath) && file_exists(public_path('storage/' . $instituteLogoPath)))
        <img class="em-inst-logo" src="{{ url('storage/' . $instituteLogoPath) }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @elseif(!empty($instituteLogoUrl))
        <img class="em-inst-logo" src="{{ $instituteLogoUrl }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @else
        <div class="em-inst-logo-fallback">{{ strtoupper(substr($instituteName, 0, 1)) }}</div>
      @endif
      <p class="em-inst-name">{{ $instituteName }}</p>
      <p class="em-inst-sub">Fee Reminder</p>
    </td></tr>
    <tr><td class="em-banner"></td></tr>

    <!-- BODY -->
    <tr><td class="em-body">
      @if($stage == 'upcoming')
        <div class="em-icon" style="background:#e6f9fa;color:#00A7B5;">&#128197;</div>
        <h1 class="em-title">Fee Due Soon</h1>
        <p class="em-sub">A friendly reminder that your fee payment is coming up.</p>
      @elseif($stage == 'due_today')
        <div class="em-icon" style="background:#fff8e6;color:#f5a623;">&#9200;</div>
        <h1 class="em-title">Fee Due Today</h1>
        <p class="em-sub">Your fee payment is due today.</p>
      @else
        <div class="em-icon" style="background:#fdeceb;color:#d9534f;">&#10071;</div>
        <h1 class="em-title">Fee Payment Overdue</h1>
        <p class="em-sub">Your fee payment is now {{ $daysOverdue }} day{{ $daysOverdue == 1 ? '' : 's' }} overdue.</p>
      @endif

      <p>Hi <strong>{{ $studentName }}</strong>,</p>
      <p>
        @if($stage == 'upcoming')
          This is a reminder that a fee payment of <strong>₹{{ number_format($dueAmount, 2) }}</strong> is due on <strong>{{ $dueDate }}</strong>.
        @elseif($stage == 'due_today')
          Your fee payment of <strong>₹{{ number_format($dueAmount, 2) }}</strong> is due today, <strong>{{ $dueDate }}</strong>.
        @else
          Your fee payment of <strong>₹{{ number_format($dueAmount, 2) }}</strong> was due on <strong>{{ $dueDate }}</strong> and is still pending. Please pay at the earliest to avoid any interruption to your services.
        @endif
      </p>

      <table class="em-cred" role="presentation">
        <tr><td class="k">Amount Due</td><td>₹{{ number_format($dueAmount, 2) }}</td></tr>
        <tr><td class="k">Due Date</td><td>{{ $dueDate }}</td></tr>
      </table>

      <div class="em-center"><a href="{{ $paymentUrl }}" class="em-btn">Pay Now</a></div>
      <div class="em-note">For any queries regarding this reminder, please contact your institute directly.</div>
    </td></tr>

    <!-- FOOTER -->
    <tr><td class="em-footer-min">
      <p class="gen">Generated by <strong>Tuoora</strong></p>
    </td></tr>
  </table>
</td></tr>
</table>
@endsection
