@extends('layouts.email')

@section('content')
<table role="presentation" class="em-wrap" width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center">
  <table role="presentation" class="em-card" width="600" cellpadding="0" cellspacing="0">
    <!-- INSTITUTE HEADER -->
    <tr><td class="em-header-inst">
      @if(!empty($instituteLogoPath) && file_exists(public_path('storage/' . $instituteLogoPath)))
        <img class="em-inst-logo" src="{{ url('storage/' . $instituteLogoPath) }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @elseif(!empty($instituteLogoUrl))
        <img class="em-inst-logo" src="{{ $instituteLogoUrl }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @else
        <div class="em-inst-logo-fallback">{{ strtoupper(substr($instituteName, 0, 1)) }}</div>
      @endif
      <p class="em-inst-name">{{ $instituteName }}</p>
      <p class="em-inst-sub">Attendance Alert</p>
    </td></tr>
    <tr><td class="em-banner"></td></tr>

    <!-- BODY -->
    <tr><td class="em-body">
      <div class="em-icon" style="background:#fdeceb;color:#d9534f;">&#9888;</div>
      <h1 class="em-title">Low Attendance Alert</h1>
      <p class="em-sub">{{ $studentName }}'s attendance has dropped below {{ $threshold }}%.</p>

      <p>Hi,</p>
      <p>
        Over the last {{ $windowDays }} days, <strong>{{ $studentName }}</strong>'s attendance has been
        <strong style="color:#d9534f;">{{ $attendancePercentage }}%</strong>, which is below the {{ $threshold }}% attendance guideline.
        Please help ensure regular attendance going forward.
      </p>

      <div class="em-center"><a href="{{ $profileUrl }}" class="em-btn">View Attendance Details</a></div>
    </td></tr>

    <!-- FOOTER -->
    <tr><td class="em-footer-min">
      <p class="gen">Generated by <strong>Tuoora</strong></p>
    </td></tr>
  </table>
</td></tr>
</table>
@endsection
