@extends('layouts.email')

@section('content')
<table role="presentation" class="em-wrap" width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center">
  <table role="presentation" class="em-card" width="600" cellpadding="0" cellspacing="0">
    <!-- INSTITUTE HEADER -->
    <tr><td class="em-header-inst">
      @if(!empty($instituteLogoPath) && file_exists(public_path('storage/' . $instituteLogoPath)))
        <img class="em-inst-logo" src="{{ url('storage/' . $instituteLogoPath) }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @elseif(!empty($instituteLogoUrl))
        <img class="em-inst-logo" src="{{ $instituteLogoUrl }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @else
        <div class="em-inst-logo-fallback">{{ strtoupper(substr($instituteName, 0, 1)) }}</div>
      @endif
      <p class="em-inst-name">{{ $instituteName }}</p>
      <p class="em-inst-sub">Weekly Progress Digest</p>
    </td></tr>
    <tr><td class="em-banner"></td></tr>

    <!-- BODY -->
    <tr><td class="em-body">
      <div class="em-icon" style="background:#e6f9fa;color:#00A7B5;">&#128202;</div>
      <h1 class="em-title">{{ $studentName }}'s Weekly Summary</h1>
      <p class="em-sub">{{ $periodLabel }}</p>

      <table class="em-cred" role="presentation">
        <tr><td class="k">Attendance</td><td>{{ $attendancePercentage }}%</td></tr>
        <tr><td class="k">Homework Completed</td><td>{{ $homeworkCompletion['completed'] }} / {{ $homeworkCompletion['total'] }}</td></tr>
        <tr><td class="k">Upcoming Exams</td><td>{{ count($upcomingExams) }}</td></tr>
        <tr><td class="k">Fee Status</td>
          <td>
            @if($feeStatus == 'Full Paid' || $feeStatus == 'No Fee')
              <span style="color:#1f9d55;font-weight:600;">{{ $feeStatus }}</span>
            @else
              <span style="color:#d9534f;font-weight:600;">{{ $feeStatus }} (₹{{ number_format($feeBalance, 2) }})</span>
            @endif
          </td>
        </tr>
      </table>

      @if(count($upcomingExams) > 0)
        <p style="font-weight:600;color:#0f172a;margin-bottom:8px;">Upcoming Exams</p>
        <table class="em-inv" role="presentation">
          <tr><th>Exam</th><th style="text-align:right;">Date</th></tr>
          @foreach($upcomingExams as $exam)
            <tr><td>{{ $exam['title'] }}</td><td style="text-align:right;">{{ $exam['date'] }}</td></tr>
          @endforeach
        </table>
      @endif

      <div class="em-center"><a href="{{ $profileUrl }}" class="em-btn">View Full Report</a></div>
    </td></tr>

    <!-- FOOTER -->
    <tr><td class="em-footer-min">
      <p class="gen">Generated by <strong>Tuoora</strong></p>
    </td></tr>
  </table>
</td></tr>
</table>
@endsection
