@extends('layouts.email')

@section('content')
<table role="presentation" class="em-wrap" width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center">
  <table role="presentation" class="em-card" width="600" cellpadding="0" cellspacing="0">
    <!-- INSTITUTE HEADER -->
    <tr><td class="em-header-inst">
      @if(!empty($instituteLogoPath) && file_exists(public_path('storage/' . $instituteLogoPath)))
        <img class="em-inst-logo" src="{{ url('storage/' . $instituteLogoPath) }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @elseif(!empty($instituteLogoUrl))
        <img class="em-inst-logo" src="{{ $instituteLogoUrl }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @else
        <div class="em-inst-logo-fallback">{{ strtoupper(substr($instituteName, 0, 1)) }}</div>
      @endif
      <p class="em-inst-name">{{ $instituteName }}</p>
      <p class="em-inst-sub">Staff Salary Payslip</p>
    </td></tr>
    <tr><td class="em-banner"></td></tr>
    
    <!-- BODY -->
    <tr><td class="em-body">
      <div class="em-icon" style="background:#fff7ed;color:#ea580c;">&#128181;</div>
      <h1 class="em-title">Salary Slip Available</h1>
      <p class="em-sub">Salary payout record for <strong>{{ $periodText }}</strong> has been processed by {{ $instituteName }}.</p>
      
      <p>Hi <strong>{{ $staffName }}</strong>,</p>
      <p>Your salary details for <strong>{{ $periodText }}</strong> have been recorded. Below is the summary of your salary breakdown:</p>
      
      <!-- Salary Metadata -->
      <table class="em-meta" role="presentation" style="margin-bottom: 16px;">
        <tr>
          <td>Employee: <strong>{{ $staffName }}</strong> ({{ $employeeId }})</td>
          <td class="r">Payment Date: <strong>{{ $paymentDate }}</strong></td>
        </tr>
        <tr>
          <td>Department: <strong>{{ $departmentName }}</strong></td>
          <td class="r">Payment Method: <strong>{{ $paymentMethod }}</strong></td>
        </tr>
        <tr>
          <td>Status: 
            @if(strtolower($status) == 'paid')
              <span style="color:#16a34a;font-weight:700;background:#dcfce7;padding:2px 8px;border-radius:4px;font-size:11px;">PAID</span>
            @else
              <span style="color:#d97706;font-weight:700;background:#fef3c7;padding:2px 8px;border-radius:4px;font-size:11px;">{{ strtoupper($status) }}</span>
            @endif
          </td>
          <td class="r">Period: <strong>{{ $periodText }}</strong></td>
        </tr>
      </table>
      
      <!-- Salary Breakdown Table -->
      <table class="em-inv" role="presentation">
        <tr>
          <th>Component</th>
          <th style="text-align:right;">Amount (INR)</th>
        </tr>
        <tr>
          <td>Base Salary</td>
          <td style="text-align:right;">&#8377; {{ number_format($baseSalary, 2) }}</td>
        </tr>
        @if($bonus > 0)
        <tr>
          <td style="color:#16a34a;">+ Bonus / Allowances</td>
          <td style="text-align:right;color:#16a34a;">&#8377; {{ number_format($bonus, 2) }}</td>
        </tr>
        @endif
        @if($deductions > 0)
        <tr>
          <td style="color:#dc2626;">- Deductions</td>
          <td style="text-align:right;color:#dc2626;">&#8377; {{ number_format($deductions, 2) }}</td>
        </tr>
        @endif
        <tr class="total" style="background:#fff7ed;border-top:2px solid #fdba74;">
          <td style="color:#9a3412;font-size:15px;"><strong>Net Paid Salary</strong></td>
          <td style="text-align:right;color:#9a3412;font-size:16px;"><strong>&#8377; {{ number_format($netSalary, 2) }}</strong></td>
        </tr>
      </table>
      
      @if(!empty($notes))
        <div style="margin-top: 16px; padding: 10px 14px; background: #f8fafc; border-left: 4px solid #cbd5e1; border-radius: 4px; font-size: 12px; color: #475569;">
          <strong>Notes:</strong> {{ $notes }}
        </div>
      @endif

      <div style="margin-top: 20px; padding: 12px 14px; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; font-size: 12px; color: #166534; line-height: 1.5;">
        <span style="font-weight: bold;">&#128206; Attached PDF:</span> A complete PDF copy of your Salary Slip has been attached to this email for your records.
      </div>
      
      <p style="margin-top: 20px; color: #64748b; font-size: 13px; line-height: 1.6;">
        For any questions or discrepancies regarding your compensation, please contact the institute accounts or administration team.
      </p>
    </td></tr>
    
    <!-- FOOTER -->
    <tr><td class="em-footer-min">
      <p class="gen">Generated by <strong>Tuoora</strong></p>
    </td></tr>
  </table>
</td></tr>
</table>
@endsection
