@extends('layouts.email')

@section('content')
<table role="presentation" class="em-wrap" width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center">
  <table role="presentation" class="em-card" width="600" cellpadding="0" cellspacing="0">
    <!-- INSTITUTE HEADER -->
    <tr><td class="em-header-inst">
      @if(!empty($instituteLogoUrl))
        <img class="em-inst-logo" src="{{ $instituteLogoUrl }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @else
        <div class="em-inst-logo-fallback">{{ strtoupper(substr($instituteName, 0, 1)) }}</div>
      @endif
      <p class="em-inst-name">{{ $instituteName }}</p>
      <p class="em-inst-sub">Student Account Created</p>
    </td></tr>
    <tr><td class="em-banner"></td></tr>
    
    <!-- BODY -->
    <tr><td class="em-body">
      <div class="em-icon" style="background:#e6f3f1;color:#1f7a6e;">&#127891;</div>
      <h1 class="em-title">Welcome to Tuoora!</h1>
      <p class="em-sub">Your student account has been created by {{ $instituteName }}.</p>
      
      <p>Hi <strong>{{ $studentName }}</strong>,</p>
      <p>An account has been created for you. Use the credentials below to log in to the Tuoora Student App:</p>
      
      <table class="em-cred" role="presentation">
        <tr><td class="k">Login Email</td><td>{{ $studentEmail }}</td></tr>
        <tr><td class="k">Password</td><td><strong>{{ $tempPassword }}</strong></td></tr>
        <tr><td class="k">Institute</td><td>{{ $instituteName }}</td></tr>
      </table>
      
      <div class="em-note">For your security, please change your password after your first login.</div>
      <div class="em-center"><a href="{{ $studentAppUrl }}" class="em-btn">Download Student App</a></div>
      <p style="text-align:center;font-size:13px;color:#64748b;">
        Available on <a href="{{ $playstoreUrl }}" style="color:#1f7a6e;">Google Play</a> &nbsp;·&nbsp; <a href="{{ $appstoreUrl }}" style="color:#1f7a6e;">App Store</a>
      </p>
    </td></tr>
    
    <!-- FOOTER -->
    <tr><td class="em-footer-min">
      <p class="gen">Generated by <strong>Tuoora</strong></p>
    </td></tr>
  </table>
</td></tr>
</table>
@endsection
