@extends('layouts.email')

@section('content')
<table role="presentation" class="em-wrap" width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center">
  <table role="presentation" class="em-card" width="600" cellpadding="0" cellspacing="0">
    <!-- INSTITUTE HEADER -->
    <tr><td class="em-header-inst">
      @if(!empty($instituteLogoPath) && file_exists(public_path('storage/' . $instituteLogoPath)))
        <img class="em-inst-logo" src="{{ url('storage/' . $instituteLogoPath) }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @elseif(!empty($instituteLogoUrl))
        <img class="em-inst-logo" src="{{ $instituteLogoUrl }}" alt="{{ $instituteName }}" style="max-height: 56px;">
      @else
        <div class="em-inst-logo-fallback">{{ strtoupper(substr($instituteName, 0, 1)) }}</div>
      @endif
      <p class="em-inst-name">{{ $instituteName }}</p>
      <p class="em-inst-sub">Account Password Update</p>
    </td></tr>
    <tr><td class="em-banner"></td></tr>
    
    <!-- BODY -->
    <tr><td class="em-body">
      <div class="em-icon" style="background:#fff2eb;color:#ff6600;">&#128274;</div>
      <h1 class="em-title">Your Student Password</h1>
      <p class="em-sub">Your student account password has been updated/retrieved by your institute.</p>
      
      <p>Hi <strong>{{ $studentName }}</strong>,</p>
      <p>The password for your Tuoora student app account associated with this email has been updated. Please find your credentials below:</p>
      
      <table class="em-cred" role="presentation">
        <tr><td class="k">Login Email</td><td>{{ $studentEmail }}</td></tr>
        <tr><td class="k">Password</td><td><strong>{{ $password }}</strong></td></tr>
        <tr><td class="k">Institute</td><td>{{ $instituteName }}</td></tr>
      </table>
      
      <div class="em-note">For your security, please log in and change your password to something secure and memorable.</div>
      <p style="text-align:center;font-size:13px;color:#64748b;">
        If you did not request this change, please contact your institute administration immediately.
      </p>
    </td></tr>
    
    <!-- FOOTER -->
    <tr><td class="em-footer-min">
      <p class="gen">Generated by <strong>Tuoora</strong></p>
    </td></tr>
  </table>
</td></tr>
</table>
@endsection
